# encoding: UTF-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

Country.create(:code => 93, :iso_code2 => 'AF', :iso_code3 => 'AFG ', :name => 'Afghanistan')
Country.create(:code => 355, :iso_code2 => 'AL', :iso_code3 => 'ALB ', :name => 'Albania')
Country.create(:code => 213, :iso_code2 => 'DZ', :iso_code3 => 'DZA ', :name => 'Algeria')
Country.create(:code => 1684, :iso_code2 => 'AS', :iso_code3 => 'ASM ', :name => 'American Samoa')
Country.create(:code => 376, :iso_code2 => 'AD', :iso_code3 => 'AND ', :name => 'Andorra')
Country.create(:code => 244, :iso_code2 => 'AO', :iso_code3 => 'AGO ', :name => 'Angola')
Country.create(:code => 1264, :iso_code2 => 'AI', :iso_code3 => 'AIA ', :name => 'Anguilla')
Country.create(:code => 672, :iso_code2 => 'AQ', :iso_code3 => 'ATA ', :name => 'Antarctica')
Country.create(:code => 1268, :iso_code2 => 'AG', :iso_code3 => 'ATG ', :name => 'Antigua and Barbuda')
Country.create(:code => 54, :iso_code2 => 'AR', :iso_code3 => 'ARG ', :name => 'Argentina')
Country.create(:code => 374, :iso_code2 => 'AM', :iso_code3 => 'ARM ', :name => 'Armenia')
Country.create(:code => 297, :iso_code2 => 'AW', :iso_code3 => 'ABW ', :name => 'Aruba')
Country.create(:code => 61, :iso_code2 => 'AU', :iso_code3 => 'AUS ', :name => 'Australia')
Country.create(:code => 43, :iso_code2 => 'AT', :iso_code3 => 'AUT ', :name => 'Austria')
Country.create(:code => 994, :iso_code2 => 'AZ', :iso_code3 => 'AZE ', :name => 'Azerbaijan')
Country.create(:code => 1242, :iso_code2 => 'BS', :iso_code3 => 'BHS ', :name => 'Bahamas')
Country.create(:code => 973, :iso_code2 => 'BH', :iso_code3 => 'BHR ', :name => 'Bahrain')
Country.create(:code => 880, :iso_code2 => 'BD', :iso_code3 => 'BGD ', :name => 'Bangladesh')
Country.create(:code => 1246, :iso_code2 => 'BB', :iso_code3 => 'BRB ', :name => 'Barbados')
Country.create(:code => 375, :iso_code2 => 'BY', :iso_code3 => 'BLR ', :name => 'Belarus')
Country.create(:code => 32, :iso_code2 => 'BE', :iso_code3 => 'BEL ', :name => 'Belgium')
Country.create(:code => 501, :iso_code2 => 'BZ', :iso_code3 => 'BLZ ', :name => 'Belize')
Country.create(:code => 229, :iso_code2 => 'BJ', :iso_code3 => 'BEN ', :name => 'Benin')
Country.create(:code => 1441, :iso_code2 => 'BM', :iso_code3 => 'BMU ', :name => 'Bermuda')
Country.create(:code => 975, :iso_code2 => 'BT', :iso_code3 => 'BTN ', :name => 'Bhutan')
Country.create(:code => 591, :iso_code2 => 'BO', :iso_code3 => 'BOL ', :name => 'Bolivia')
Country.create(:code => 387, :iso_code2 => 'BA', :iso_code3 => 'BIH ', :name => 'Bosnia and Herzegovina')
Country.create(:code => 267, :iso_code2 => 'BW', :iso_code3 => 'BWA ', :name => 'Botswana')
Country.create(:code => 55, :iso_code2 => 'BR', :iso_code3 => 'BRA ', :name => 'Brazil')
Country.create(:code => 1284, :iso_code2 => 'VG', :iso_code3 => 'VGB ', :name => 'British Virgin Islands')
Country.create(:code => 673, :iso_code2 => 'BN', :iso_code3 => 'BRN ', :name => 'Brunei')
Country.create(:code => 359, :iso_code2 => 'BG', :iso_code3 => 'BGR ', :name => 'Bulgaria')
Country.create(:code => 226, :iso_code2 => 'BF', :iso_code3 => 'BFA ', :name => 'Burkina Faso')
Country.create(:code => 95, :iso_code2 => 'MM', :iso_code3 => 'MMR ', :name => 'Burma (Myanmar)')
Country.create(:code => 257, :iso_code2 => 'BI', :iso_code3 => 'BDI ', :name => 'Burundi')
Country.create(:code => 855, :iso_code2 => 'KH', :iso_code3 => 'KHM ', :name => 'Cambodia')
Country.create(:code => 237, :iso_code2 => 'CM', :iso_code3 => 'CMR ', :name => 'Cameroon')
Country.create(:code => 1, :iso_code2 => 'CA', :iso_code3 => 'CAN ', :name => 'Canada')
Country.create(:code => 238, :iso_code2 => 'CV', :iso_code3 => 'CPV ', :name => 'Cape Verde')
Country.create(:code => 1345, :iso_code2 => 'KY', :iso_code3 => 'CYM ', :name => 'Cayman Islands')
Country.create(:code => 236, :iso_code2 => 'CF', :iso_code3 => 'CAF ', :name => 'Central African Republic')
Country.create(:code => 235, :iso_code2 => 'TD', :iso_code3 => 'TCD ', :name => 'Chad')
Country.create(:code => 56, :iso_code2 => 'CL', :iso_code3 => 'CHL ', :name => 'Chile')
Country.create(:code => 86, :iso_code2 => 'CN', :iso_code3 => 'CHN ', :name => 'China')
Country.create(:code => 61, :iso_code2 => 'CX', :iso_code3 => 'CXR ', :name => 'Christmas Island')
Country.create(:code => 61, :iso_code2 => 'CC', :iso_code3 => 'CCK ', :name => 'Cocos (Keeling) Islands')
Country.create(:code => 57, :iso_code2 => 'CO', :iso_code3 => 'COL ', :name => 'Colombia')
Country.create(:code => 269, :iso_code2 => 'KM', :iso_code3 => 'COM ', :name => 'Comoros')
Country.create(:code => 682, :iso_code2 => 'CK', :iso_code3 => 'COK ', :name => 'Cook Islands')
Country.create(:code => 506, :iso_code2 => 'CR', :iso_code3 => 'CRC ', :name => 'Costa Rica')
Country.create(:code => 385, :iso_code2 => 'HR', :iso_code3 => 'HRV ', :name => 'Croatia')
Country.create(:code => 53, :iso_code2 => 'CU', :iso_code3 => 'CUB ', :name => 'Cuba')
Country.create(:code => 357, :iso_code2 => 'CY', :iso_code3 => 'CYP ', :name => 'Cyprus')
Country.create(:code => 420, :iso_code2 => 'CZ', :iso_code3 => 'CZE ', :name => 'Czech Republic')
Country.create(:code => 243, :iso_code2 => 'CD', :iso_code3 => 'COD ', :name => 'Democratic Republic of the Congo')
Country.create(:code => 45, :iso_code2 => 'DK', :iso_code3 => 'DNK ', :name => 'Denmark')
Country.create(:code => 253, :iso_code2 => 'DJ', :iso_code3 => 'DJI ', :name => 'Djibouti')
Country.create(:code => 1767, :iso_code2 => 'DM', :iso_code3 => 'DMA ', :name => 'Dominica')
Country.create(:code => 1809, :iso_code2 => 'DO', :iso_code3 => 'DOM ', :name => 'Dominican Republic')
Country.create(:code => 593, :iso_code2 => 'EC', :iso_code3 => 'ECU ', :name => 'Ecuador')
Country.create(:code => 20, :iso_code2 => 'EG', :iso_code3 => 'EGY ', :name => 'Egypt')
Country.create(:code => 503, :iso_code2 => 'SV', :iso_code3 => 'SLV ', :name => 'El Salvador')
Country.create(:code => 240, :iso_code2 => 'GQ', :iso_code3 => 'GNQ ', :name => 'Equatorial Guinea')
Country.create(:code => 291, :iso_code2 => 'ER', :iso_code3 => 'ERI ', :name => 'Eritrea')
Country.create(:code => 372, :iso_code2 => 'EE', :iso_code3 => 'EST ', :name => 'Estonia')
Country.create(:code => 251, :iso_code2 => 'ET', :iso_code3 => 'ETH ', :name => 'Ethiopia')
Country.create(:code => 500, :iso_code2 => 'FK', :iso_code3 => 'FLK ', :name => 'Falkland Islands')
Country.create(:code => 298, :iso_code2 => 'FO', :iso_code3 => 'FRO ', :name => 'Faroe Islands')
Country.create(:code => 679, :iso_code2 => 'FJ', :iso_code3 => 'FJI ', :name => 'Fiji')
Country.create(:code => 358, :iso_code2 => 'FI', :iso_code3 => 'FIN ', :name => 'Finland')
Country.create(:code => 33, :iso_code2 => 'FR', :iso_code3 => 'FRA ', :name => 'France')
Country.create(:code => 689, :iso_code2 => 'PF', :iso_code3 => 'PYF ', :name => 'French Polynesia')
Country.create(:code => 241, :iso_code2 => 'GA', :iso_code3 => 'GAB ', :name => 'Gabon')
Country.create(:code => 220, :iso_code2 => 'GM', :iso_code3 => 'GMB ', :name => 'Gambia')
Country.create(:code => 995, :iso_code2 => 'GE', :iso_code3 => 'GEO ', :name => 'Georgia')
Country.create(:code => 49, :iso_code2 => 'DE', :iso_code3 => 'DEU ', :name => 'Germany')
Country.create(:code => 233, :iso_code2 => 'GH', :iso_code3 => 'GHA ', :name => 'Ghana')
Country.create(:code => 350, :iso_code2 => 'GI', :iso_code3 => 'GIB ', :name => 'Gibraltar')
Country.create(:code => 30, :iso_code2 => 'GR', :iso_code3 => 'GRC ', :name => 'Greece')
Country.create(:code => 299, :iso_code2 => 'GL', :iso_code3 => 'GRL ', :name => 'Greenland')
Country.create(:code => 1473, :iso_code2 => 'GD', :iso_code3 => 'GRD ', :name => 'Grenada')
Country.create(:code => 1671, :iso_code2 => 'GU', :iso_code3 => 'GUM ', :name => 'Guam')
Country.create(:code => 502, :iso_code2 => 'GT', :iso_code3 => 'GTM ', :name => 'Guatemala')
Country.create(:code => 224, :iso_code2 => 'GN', :iso_code3 => 'GIN ', :name => 'Guinea')
Country.create(:code => 245, :iso_code2 => 'GW', :iso_code3 => 'GNB ', :name => 'Guinea-Bissau')
Country.create(:code => 592, :iso_code2 => 'GY', :iso_code3 => 'GUY ', :name => 'Guyana')
Country.create(:code => 509, :iso_code2 => 'HT', :iso_code3 => 'HTI ', :name => 'Haiti')
Country.create(:code => 39, :iso_code2 => 'VA', :iso_code3 => 'VAT ', :name => 'Holy See (Vatican City)')
Country.create(:code => 504, :iso_code2 => 'HN', :iso_code3 => 'HND ', :name => 'Honduras')
Country.create(:code => 852, :iso_code2 => 'HK', :iso_code3 => 'HKG ', :name => 'Hong Kong')
Country.create(:code => 36, :iso_code2 => 'HU', :iso_code3 => 'HUN ', :name => 'Hungary')
Country.create(:code => 354, :iso_code2 => 'IS', :iso_code3 => 'IS ', :name => 'Iceland')
Country.create(:code => 91, :iso_code2 => 'IN', :iso_code3 => 'IND ', :name => 'India')
Country.create(:code => 62, :iso_code2 => 'ID', :iso_code3 => 'IDN ', :name => 'Indonesia')
Country.create(:code => 98, :iso_code2 => 'IR', :iso_code3 => 'IRN ', :name => 'Iran')
Country.create(:code => 964, :iso_code2 => 'IQ', :iso_code3 => 'IRQ ', :name => 'Iraq')
Country.create(:code => 353, :iso_code2 => 'IE', :iso_code3 => 'IRL ', :name => 'Ireland')
Country.create(:code => 44, :iso_code2 => 'IM', :iso_code3 => 'IMN ', :name => 'Isle of Man')
Country.create(:code => 972, :iso_code2 => 'IL', :iso_code3 => 'ISR ', :name => 'Israel')
Country.create(:code => 39, :iso_code2 => 'IT', :iso_code3 => 'ITA ', :name => 'Italy')
Country.create(:code => 225, :iso_code2 => 'CI', :iso_code3 => 'CIV ', :name => 'Ivory Coast')
Country.create(:code => 1876, :iso_code2 => 'JM', :iso_code3 => 'JAM ', :name => 'Jamaica')
Country.create(:code => 81, :iso_code2 => 'JP', :iso_code3 => 'JPN ', :name => 'Japan')
Country.create(:code => 962, :iso_code2 => 'JO', :iso_code3 => 'JOR ', :name => 'Jordan')
Country.create(:code => 7, :iso_code2 => 'KZ', :iso_code3 => 'KAZ ', :name => 'Kazakhstan')
Country.create(:code => 254, :iso_code2 => 'KE', :iso_code3 => 'KEN ', :name => 'Kenya')
Country.create(:code => 686, :iso_code2 => 'KI', :iso_code3 => 'KIR ', :name => 'Kiribati')
Country.create(:code => 965, :iso_code2 => 'KW', :iso_code3 => 'KWT ', :name => 'Kuwait')
Country.create(:code => 996, :iso_code2 => 'KG', :iso_code3 => 'KGZ ', :name => 'Kyrgyzstan')
Country.create(:code => 856, :iso_code2 => 'LA', :iso_code3 => 'LAO ', :name => 'Laos')
Country.create(:code => 371, :iso_code2 => 'LV', :iso_code3 => 'LVA ', :name => 'Latvia')
Country.create(:code => 961, :iso_code2 => 'LB', :iso_code3 => 'LBN ', :name => 'Lebanon')
Country.create(:code => 266, :iso_code2 => 'LS', :iso_code3 => 'LSO ', :name => 'Lesotho')
Country.create(:code => 231, :iso_code2 => 'LR', :iso_code3 => 'LBR ', :name => 'Liberia')
Country.create(:code => 218, :iso_code2 => 'LY', :iso_code3 => 'LBY ', :name => 'Libya')
Country.create(:code => 423, :iso_code2 => 'LI', :iso_code3 => 'LIE ', :name => 'Liechtenstein')
Country.create(:code => 370, :iso_code2 => 'LT', :iso_code3 => 'LTU ', :name => 'Lithuania')
Country.create(:code => 352, :iso_code2 => 'LU', :iso_code3 => 'LUX ', :name => 'Luxembourg')
Country.create(:code => 853, :iso_code2 => 'MO', :iso_code3 => 'MAC ', :name => 'Macau')
Country.create(:code => 389, :iso_code2 => 'MK', :iso_code3 => 'MKD ', :name => 'Macedonia')
Country.create(:code => 261, :iso_code2 => 'MG', :iso_code3 => 'MDG ', :name => 'Madagascar')
Country.create(:code => 265, :iso_code2 => 'MW', :iso_code3 => 'MWI ', :name => 'Malawi')
Country.create(:code => 60, :iso_code2 => 'MY', :iso_code3 => 'MYS ', :name => 'Malaysia')
Country.create(:code => 960, :iso_code2 => 'MV', :iso_code3 => 'MDV ', :name => 'Maldives')
Country.create(:code => 223, :iso_code2 => 'ML', :iso_code3 => 'MLI ', :name => 'Mali')
Country.create(:code => 356, :iso_code2 => 'MT', :iso_code3 => 'MLT ', :name => 'Malta')
Country.create(:code => 692, :iso_code2 => 'MH', :iso_code3 => 'MHL ', :name => 'Marshall Islands')
Country.create(:code => 222, :iso_code2 => 'MR', :iso_code3 => 'MRT ', :name => 'Mauritania')
Country.create(:code => 230, :iso_code2 => 'MU', :iso_code3 => 'MUS ', :name => 'Mauritius')
Country.create(:code => 262, :iso_code2 => 'YT', :iso_code3 => 'MYT ', :name => 'Mayotte')
Country.create(:code => 52, :iso_code2 => 'MX', :iso_code3 => 'MEX ', :name => 'Mexico')
Country.create(:code => 691, :iso_code2 => 'FM', :iso_code3 => 'FSM ', :name => 'Micronesia')
Country.create(:code => 373, :iso_code2 => 'MD', :iso_code3 => 'MDA ', :name => 'Moldova')
Country.create(:code => 377, :iso_code2 => 'MC', :iso_code3 => 'MCO ', :name => 'Monaco')
Country.create(:code => 976, :iso_code2 => 'MN', :iso_code3 => 'MNG ', :name => 'Mongolia')
Country.create(:code => 382, :iso_code2 => 'ME', :iso_code3 => 'MNE ', :name => 'Montenegro')
Country.create(:code => 1664, :iso_code2 => 'MS', :iso_code3 => 'MSR ', :name => 'Montserrat')
Country.create(:code => 212, :iso_code2 => 'MA', :iso_code3 => 'MAR ', :name => 'Morocco')
Country.create(:code => 258, :iso_code2 => 'MZ', :iso_code3 => 'MOZ ', :name => 'Mozambique')
Country.create(:code => 264, :iso_code2 => 'NA', :iso_code3 => 'NAM ', :name => 'Namibia')
Country.create(:code => 674, :iso_code2 => 'NR', :iso_code3 => 'NRU ', :name => 'Nauru')
Country.create(:code => 977, :iso_code2 => 'NP', :iso_code3 => 'NPL ', :name => 'Nepal')
Country.create(:code => 31, :iso_code2 => 'NL', :iso_code3 => 'NLD ', :name => 'Netherlands')
Country.create(:code => 599, :iso_code2 => 'AN', :iso_code3 => 'ANT ', :name => 'Netherlands Antilles')
Country.create(:code => 687, :iso_code2 => 'NC', :iso_code3 => 'NCL ', :name => 'New Caledonia')
Country.create(:code => 64, :iso_code2 => 'NZ', :iso_code3 => 'NZL ', :name => 'New Zealand')
Country.create(:code => 505, :iso_code2 => 'NI', :iso_code3 => 'NIC ', :name => 'Nicaragua')
Country.create(:code => 227, :iso_code2 => 'NE', :iso_code3 => 'NER ', :name => 'Niger')
Country.create(:code => 234, :iso_code2 => 'NG', :iso_code3 => 'NGA ', :name => 'Nigeria')
Country.create(:code => 683, :iso_code2 => 'NU', :iso_code3 => 'NIU ', :name => 'Niue')
Country.create(:code => 850, :iso_code2 => 'KP', :iso_code3 => 'PRK ', :name => 'North Korea')
Country.create(:code => 1670, :iso_code2 => 'MP', :iso_code3 => 'MNP ', :name => 'Northern Mariana Islands')
Country.create(:code => 47, :iso_code2 => 'NO', :iso_code3 => 'NOR ', :name => 'Norway')
Country.create(:code => 968, :iso_code2 => 'OM', :iso_code3 => 'OMN ', :name => 'Oman')
Country.create(:code => 92, :iso_code2 => 'PK', :iso_code3 => 'PAK ', :name => 'Pakistan')
Country.create(:code => 680, :iso_code2 => 'PW', :iso_code3 => 'PLW ', :name => 'Palau')
Country.create(:code => 507, :iso_code2 => 'PA', :iso_code3 => 'PAN ', :name => 'Panama')
Country.create(:code => 675, :iso_code2 => 'PG', :iso_code3 => 'PNG ', :name => 'Papua New Guinea')
Country.create(:code => 595, :iso_code2 => 'PY', :iso_code3 => 'PRY ', :name => 'Paraguay')
Country.create(:code => 51, :iso_code2 => 'PE', :iso_code3 => 'PER ', :name => 'Peru')
Country.create(:code => 63, :iso_code2 => 'PH', :iso_code3 => 'PHL ', :name => 'Philippines')
Country.create(:code => 870, :iso_code2 => 'PN', :iso_code3 => 'PCN ', :name => 'Pitcairn Islands')
Country.create(:code => 48, :iso_code2 => 'PL', :iso_code3 => 'POL ', :name => 'Poland')
Country.create(:code => 351, :iso_code2 => 'PT', :iso_code3 => 'PRT ', :name => 'Portugal')
Country.create(:code => 1, :iso_code2 => 'PR', :iso_code3 => 'PRI ', :name => 'Puerto Rico')
Country.create(:code => 974, :iso_code2 => 'QA', :iso_code3 => 'QAT ', :name => 'Qatar')
Country.create(:code => 242, :iso_code2 => 'CG', :iso_code3 => 'COG ', :name => 'Republic of the Congo')
Country.create(:code => 40, :iso_code2 => 'RO', :iso_code3 => 'ROU ', :name => 'Romania')
Country.create(:code => 7, :iso_code2 => 'RU', :iso_code3 => 'RUS ', :name => 'Russia')
Country.create(:code => 250, :iso_code2 => 'RW', :iso_code3 => 'RWA ', :name => 'Rwanda')
Country.create(:code => 590, :iso_code2 => 'BL', :iso_code3 => 'BLM ', :name => 'Saint Barthelemy')
Country.create(:code => 290, :iso_code2 => 'SH', :iso_code3 => 'SHN ', :name => 'Saint Helena')
Country.create(:code => 1869, :iso_code2 => 'KN', :iso_code3 => 'KNA ', :name => 'Saint Kitts and Nevis')
Country.create(:code => 1758, :iso_code2 => 'LC', :iso_code3 => 'LCA ', :name => 'Saint Lucia')
Country.create(:code => 1599, :iso_code2 => 'MF', :iso_code3 => 'MAF ', :name => 'Saint Martin')
Country.create(:code => 508, :iso_code2 => 'PM', :iso_code3 => 'SPM ', :name => 'Saint Pierre and Miquelon')
Country.create(:code => 1784, :iso_code2 => 'VC', :iso_code3 => 'VCT ', :name => 'Saint Vincent and the Grenadines')
Country.create(:code => 685, :iso_code2 => 'WS', :iso_code3 => 'WSM ', :name => 'Samoa')
Country.create(:code => 378, :iso_code2 => 'SM', :iso_code3 => 'SMR ', :name => 'San Marino')
Country.create(:code => 239, :iso_code2 => 'ST', :iso_code3 => 'STP ', :name => 'Sao Tome and Principe')
Country.create(:code => 966, :iso_code2 => 'SA', :iso_code3 => 'SAU ', :name => 'Saudi Arabia')
Country.create(:code => 221, :iso_code2 => 'SN', :iso_code3 => 'SEN ', :name => 'Senegal')
Country.create(:code => 381, :iso_code2 => 'RS', :iso_code3 => 'SRB ', :name => 'Serbia')
Country.create(:code => 248, :iso_code2 => 'SC', :iso_code3 => 'SYC ', :name => 'Seychelles')
Country.create(:code => 232, :iso_code2 => 'SL', :iso_code3 => 'SLE ', :name => 'Sierra Leone')
Country.create(:code => 65, :iso_code2 => 'SG', :iso_code3 => 'SGP ', :name => 'Singapore')
Country.create(:code => 421, :iso_code2 => 'SK', :iso_code3 => 'SVK ', :name => 'Slovakia')
Country.create(:code => 386, :iso_code2 => 'SI', :iso_code3 => 'SVN ', :name => 'Slovenia')
Country.create(:code => 677, :iso_code2 => 'SB', :iso_code3 => 'SLB ', :name => 'Solomon Islands')
Country.create(:code => 252, :iso_code2 => 'SO', :iso_code3 => 'SOM ', :name => 'Somalia')
Country.create(:code => 27, :iso_code2 => 'ZA', :iso_code3 => 'ZAF ', :name => 'South Africa')
Country.create(:code => 82, :iso_code2 => 'KR', :iso_code3 => 'KOR ', :name => 'South Korea')
Country.create(:code => 34, :iso_code2 => 'ES', :iso_code3 => 'ESP ', :name => 'Spain')
Country.create(:code => 94, :iso_code2 => 'LK', :iso_code3 => 'LKA ', :name => 'Sri Lanka')
Country.create(:code => 249, :iso_code2 => 'SD', :iso_code3 => 'SDN ', :name => 'Sudan')
Country.create(:code => 597, :iso_code2 => 'SR', :iso_code3 => 'SUR ', :name => 'Suriname')
Country.create(:code => 268, :iso_code2 => 'SZ', :iso_code3 => 'SWZ ', :name => 'Swaziland')
Country.create(:code => 46, :iso_code2 => 'SE', :iso_code3 => 'SWE ', :name => 'Sweden')
Country.create(:code => 41, :iso_code2 => 'CH', :iso_code3 => 'CHE ', :name => 'Switzerland')
Country.create(:code => 963, :iso_code2 => 'SY', :iso_code3 => 'SYR ', :name => 'Syria')
Country.create(:code => 886, :iso_code2 => 'TW', :iso_code3 => 'TWN ', :name => 'Taiwan')
Country.create(:code => 992, :iso_code2 => 'TJ', :iso_code3 => 'TJK ', :name => 'Tajikistan')
Country.create(:code => 255, :iso_code2 => 'TZ', :iso_code3 => 'TZA ', :name => 'Tanzania')
Country.create(:code => 66, :iso_code2 => 'TH', :iso_code3 => 'THA ', :name => 'Thailand')
Country.create(:code => 670, :iso_code2 => 'TL', :iso_code3 => 'TLS ', :name => 'Timor-Leste')
Country.create(:code => 228, :iso_code2 => 'TG', :iso_code3 => 'TGO ', :name => 'Togo')
Country.create(:code => 690, :iso_code2 => 'TK', :iso_code3 => 'TKL ', :name => 'Tokelau')
Country.create(:code => 676, :iso_code2 => 'TO', :iso_code3 => 'TON ', :name => 'Tonga')
Country.create(:code => 1868, :iso_code2 => 'TT', :iso_code3 => 'TTO ', :name => 'Trinidad and Tobago')
Country.create(:code => 216, :iso_code2 => 'TN', :iso_code3 => 'TUN ', :name => 'Tunisia')
Country.create(:code => 90, :iso_code2 => 'TR', :iso_code3 => 'TUR ', :name => 'Turkey')
Country.create(:code => 993, :iso_code2 => 'TM', :iso_code3 => 'TKM ', :name => 'Turkmenistan')
Country.create(:code => 1649, :iso_code2 => 'TC', :iso_code3 => 'TCA ', :name => 'Turks and Caicos Islands')
Country.create(:code => 688, :iso_code2 => 'TV', :iso_code3 => 'TUV ', :name => 'Tuvalu')
Country.create(:code => 256, :iso_code2 => 'UG', :iso_code3 => 'UGA ', :name => 'Uganda')
Country.create(:code => 380, :iso_code2 => 'UA', :iso_code3 => 'UKR ', :name => 'Ukraine')
Country.create(:code => 971, :iso_code2 => 'AE', :iso_code3 => 'ARE ', :name => 'United Arab Emirates')
Country.create(:code => 44, :iso_code2 => 'GB', :iso_code3 => 'GBR ', :name => 'United Kingdom')
Country.create(:code => 1, :iso_code2 => 'US', :iso_code3 => 'USA ', :name => 'United States')
Country.create(:code => 598, :iso_code2 => 'UY', :iso_code3 => 'URY ', :name => 'Uruguay')
Country.create(:code => 1340, :iso_code2 => 'VI', :iso_code3 => 'VIR ', :name => 'US Virgin Islands')
Country.create(:code => 998, :iso_code2 => 'UZ', :iso_code3 => 'UZB ', :name => 'Uzbekistan')
Country.create(:code => 678, :iso_code2 => 'VU', :iso_code3 => 'VUT ', :name => 'Vanuatu')
Country.create(:code => 58, :iso_code2 => 'VE', :iso_code3 => 'VEN ', :name => 'Venezuela')
Country.create(:code => 84, :iso_code2 => 'VN', :iso_code3 => 'VNM ', :name => 'Vietnam')
Country.create(:code => 681, :iso_code2 => 'WF', :iso_code3 => 'WLF ', :name => 'Wallis and Futuna')
Country.create(:code => 967, :iso_code2 => 'YE', :iso_code3 => 'YEM ', :name => 'Yemen')
Country.create(:code => 260, :iso_code2 => 'ZM', :iso_code3 => 'ZMB ', :name => 'Zambia')
Country.create(:code => 263, :iso_code2 => 'ZW', :iso_code3 => 'ZWE ', :name => 'Zimbabwe')

PaymentType.create(:code => 1, :name => 'Diners', :company => 'Komerci', :institution => 'Redecard')
PaymentType.create(:code => 2, :name => 'Mastercard', :company => 'Komerci', :institution => 'Redecard')
PaymentType.create(:code => 7, :name => 'Visa', :company => 'Verified by Visa', :institution => 'Cielo')
PaymentType.create(:code => 14, :name => 'Cartões Itaucard', :company => 'Itaú Shopline', :institution => 'Banco Itaú')
PaymentType.create(:code => 11, :name => 'American Express', :company => 'WebPOS', :institution => 'American Express')
PaymentType.create(:code => 8, :name => 'Visa Electron', :company => 'Verified by Visa', :institution => 'Cielo')
PaymentType.create(:code => 13, :name => 'Transferência entre contas', :company => 'Itaú Shopline', :institution => 'Banco Itaú')
PaymentType.create(:code => 15, :name => 'Boleto bancário', :company => 'Itaú Shopline', :institution => 'Banco Itaú')

PaymentMethod.create(:code => 'A01', :description => 'à vista')
PaymentMethod.create(:code => 'A02', :description => '2x sem juros')
PaymentMethod.create(:code => 'A03', :description => '32x sem juros')
PaymentMethod.create(:code => 'A04', :description => '4x sem juros')
PaymentMethod.create(:code => 'A05', :description => '5x sem juros')
PaymentMethod.create(:code => 'A06', :description => '6x sem juros')
PaymentMethod.create(:code => 'A07', :description => '7x sem juros')
PaymentMethod.create(:code => 'A08', :description => '8x sem juros')
PaymentMethod.create(:code => 'A09', :description => '9x sem juros')
PaymentMethod.create(:code => 'A10', :description => '10x sem juros')
PaymentMethod.create(:code => 'A11', :description => '11x sem juros')
PaymentMethod.create(:code => 'A12', :description => '12x sem juros')
PaymentMethod.create(:code => 'B02', :description => '2x com juros')
PaymentMethod.create(:code => 'B03', :description => '32x com juros')
PaymentMethod.create(:code => 'B04', :description => '4x com juros')
PaymentMethod.create(:code => 'B05', :description => '5x com juros')
PaymentMethod.create(:code => 'B06', :description => '6x com juros')
PaymentMethod.create(:code => 'B07', :description => '7x com juros')
PaymentMethod.create(:code => 'B08', :description => '8x com juros')
PaymentMethod.create(:code => 'B09', :description => '9x com juros')
PaymentMethod.create(:code => 'B10', :description => '10x com juros')
PaymentMethod.create(:code => 'B11', :description => '11x com juros')
PaymentMethod.create(:code => 'B12', :description => '12x com juros')

User.create(:email => 'rmaeshiro@eversystems.com', :login => 'rmaeshiro', :password => '102030', :password_confirmation => '102030', :admin => 't')